import { Activity, BookOpen, Sprout, Users } from "lucide-react";
import { getDb } from "@/lib/db/pool";

export const dynamic = "force-dynamic";

async function getOverview() {
  try {
    const db = getDb();
    if (!db) return null;
    const [[users], [activeUsers], [crops], [analyses], [articles], [recommendations], [recentUsers]] = await Promise.all([
      db.query("SELECT COUNT(*) AS total FROM users"),
      db.query("SELECT COUNT(*) AS total FROM users WHERE status = 'active'"),
      db.query("SELECT COUNT(*) AS total FROM crops"),
      db.query("SELECT COUNT(*) AS total FROM analyses"),
      db.query("SELECT COUNT(*) AS total FROM knowledge_articles"),
      db.query("SELECT COUNT(*) AS total FROM recommendations WHERE status = 'ready'"),
      db.query("SELECT id, name, email, role, status, created_at AS createdAt FROM users ORDER BY created_at DESC LIMIT 5"),
    ]);
    const value = (rows: unknown) => Number((rows as Array<{ total: number }>)[0]?.total ?? 0);
    return {
      metrics: { users: value(users), activeUsers: value(activeUsers), crops: value(crops), analyses: value(analyses), articles: value(articles), pendingRecommendations: value(recommendations) },
      recentUsers: recentUsers as Array<{ id: string; name: string; email: string; role: string; status: string; createdAt: string }>,
    };
  } catch {
    return null;
  }
}

const cards = [
  ["users", "Total users", Users, "bg-[#e0f5eb] text-[#288b69]"],
  ["activeUsers", "Active users", Activity, "bg-[#e9edff] text-[#6478d0]"],
  ["crops", "Crop records", Sprout, "bg-[#fff5dd] text-[#bd8a20]"],
  ["articles", "Knowledge articles", BookOpen, "bg-[#eee6ff] text-[#815cc6]"],
] as const;

export default async function AdminOverviewPage() {
  const data = await getOverview();
  return <section className="space-y-6"><header className="rounded-2xl bg-[#e4f4e5] p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#27715d]">Dashboard overview</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.04em] text-[#064b3b]">A clear view of your system.</h2><p className="mt-3 max-w-2xl text-base leading-7 text-[#45675e]">Monitor the real users, crop records, analyses, and knowledge content stored in AgriKMS.</p></header>{!data ? <div className="rounded-xl border border-[#e8b9a5] bg-[#fff5ef] p-5 text-[#9a3c20]">Unable to load admin metrics. Check the database connection.</div> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([key, label, Icon, tone]) => <article key={key} className="rounded-xl bg-white p-5 shadow-sm"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone}`}><Icon size={22} /></div><p className="mt-5 text-sm text-slate-500">{label}</p><strong className="mt-1 block text-3xl text-[#123d35]">{data.metrics[key]}</strong></article>)}</div><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-xl bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><h3 className="font-bold">Recent users</h3><a href="/admin/users" className="text-sm font-bold text-[#18765b]">Manage users</a></div>{data.recentUsers.length === 0 ? <p className="p-6 text-slate-500">No users have registered yet.</p> : <div className="divide-y divide-slate-100">{data.recentUsers.map((user) => <div key={user.id} className="flex items-center justify-between gap-4 px-6 py-4"><div><p className="font-semibold">{user.name}</p><p className="mt-1 text-sm text-slate-500">{user.email}</p></div><span className="rounded-full bg-[#e0f5eb] px-3 py-1 text-xs font-bold capitalize text-[#25805e]">{user.role}</span></div>)}</div>}</section><section className="rounded-xl bg-[#123d35] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#f3cf43]">Pending actions</p><h3 className="mt-3 text-2xl font-bold">{data.metrics.pendingRecommendations} recommendations ready</h3><p className="mt-3 text-sm leading-6 text-white/70">Review recommendations generated by the existing agricultural workflows.</p><a href="/admin/recommendations" className="mt-6 inline-flex items-center rounded-lg bg-white/10 px-4 py-3 text-sm font-bold hover:bg-white/20">Review records</a></section></div></>}</section>;
}
