-- Dashboard domain tables (Table definitions only)

CREATE TABLE farms (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_id CHAR(36) NOT NULL,
  name VARCHAR(160) NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE fields (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  farm_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  area_hectares DECIMAL(10,2) NULL,
  soil_type VARCHAR(100) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crop_plantings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  field_id BIGINT UNSIGNED NOT NULL,
  crop_id BIGINT UNSIGNED NOT NULL,a
  planted_on DATE NULL,
  expected_harvest_on DATE NULL,
  health_status ENUM('healthy', 'watch', 'critical') NOT NULL DEFAULT 'healthy',
  progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_articles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  author_id CHAR(36) NULL,
  crop_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  summary TEXT NOT NULL,
  body LONGTEXT NOT NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recommendations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  field_id BIGINT UNSIGNED NULL,
  crop_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  explanation TEXT NOT NULL,
  status ENUM('ready', 'dismissed', 'completed') NOT NULL DEFAULT 'ready',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL
);

CREATE TABLE weather_snapshots (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  location_id BIGINT UNSIGNED NOT NULL,
  temperature_c DECIMAL(5,2) NOT NULL,
  humidity_percent DECIMAL(5,2) NULL,
  rainfall_probability_percent DECIMAL(5,2) NULL,
  wind_kph DECIMAL(6,2) NULL,
  condition_label VARCHAR(80) NULL,
  observed_at TIMESTAMP NOT NULL
);

CREATE TABLE reports (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  farm_id BIGINT UNSIGNED NULL,
  report_type VARCHAR(80) NOT NULL,
  title VARCHAR(255) NOT NULL,
  storage_path VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  recommendation_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  read_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);