"use client";

import { Field, Recommendation } from "@/lib/db/repository";
import { AlertTriangle, CheckCircle, Compass, Droplets, Info, Layers, RefreshCw, Sprout } from "lucide-react";
import { useState } from "react";

interface DecisionEngineProps {
  fields: Field[];
  recentRecommendations: Recommendation[];
}

export default function DecisionEngine({ fields, recentRecommendations }: DecisionEngineProps) {
  const [selectedFieldId, setSelectedFieldId] = useState(fields[0]?.id || "");
  const [cropStage, setCropStage] = useState("vegetative");
  const [rainfallRecent, setRainfallRecent] = useState("Moderate (25-50mm)");
  const [observedIssues, setObservedIssues] = useState("None");

  const [isGenerating, setIsGenerating] = useState(false);
  const [activeAdvisories, setActiveAdvisories] = useState<{
    fertilizer: Recommendation | null;
    irrigation: Recommendation | null;
  } | null>(null);
  const [error, setError] = useState("");

  const currentField = fields.find((f) => f.id === selectedFieldId);

  async function handleGenerateAdvisory(e: React.FormEvent) {
    e.preventDefault();
    if (!selectedFieldId) {
      setError("Please select a field plot.");
      return;
    }
    setError("");
    setIsGenerating(true);

    try {
      const res = await fetch("/api/decision-support", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          field_id: selectedFieldId,
          crop_stage: cropStage,
          rainfall_recent: rainfallRecent,
          observed_issues: observedIssues,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to execute decision support rules.");
      }

      const data = await res.json();
      setActiveAdvisories({
        fertilizer: data.fertilizer,
        irrigation: data.irrigation,
      });
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setIsGenerating(false);
    }
  }

  return (
    <div className="space-y-8">
      {/* System Disclaimer Banner */}
      <div className="relative overflow-hidden rounded-2xl border border-amber-200 bg-gradient-to-r from-amber-50 via-yellow-50 to-amber-100/60 p-5 sm:p-6">
        <div className="flex items-start gap-4">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-500 text-white shadow-xs">
            <AlertTriangle size={22} />
          </div>
          <div>
            <h4 className="text-base font-extrabold text-amber-950">System Advisory & Heuristic Rule Disclaimer</h4>
            <p className="mt-1 text-xs leading-relaxed text-amber-900/90 sm:text-sm">
              All recommendations generated by AgriKMS are calculated using rule-based agronomic heuristics matching your field inputs against predefined soil and crop formulas. <strong>They do not replace professional on-site agronomist consultations or certified soil lab analyses.</strong> Always perform spot testing prior to large-scale chemical application.
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-8 lg:grid-cols-[1fr_1.2fr]">
        {/* Input Controls Card */}
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs">
          <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e0f5eb] text-[#16875f]">
              <Compass size={22} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-[#123d35]">Agronomic Input Parameters</h3>
              <p className="text-xs text-slate-500">Configure current plot condition</p>
            </div>
          </div>

          {error && <div className="mt-4 rounded-xl bg-[#fff5ef] p-3 text-xs text-[#9a3c20]">{error}</div>}

          <form onSubmit={handleGenerateAdvisory} className="mt-5 space-y-4">
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600">Select Field Plot *</label>
              <select
                value={selectedFieldId}
                onChange={(e) => setSelectedFieldId(e.target.value)}
                className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm font-semibold text-slate-800 outline-none focus:border-[#16875f]"
              >
                {fields.map((f) => (
                  <option key={f.id} value={f.id}>
                    {f.name} — {f.crop_name} ({f.area} ha)
                  </option>
                ))}
              </select>
            </div>

            {/* Parameter preview badges */}
            {currentField && (
              <div className="rounded-xl bg-slate-50 p-3.5 text-xs">
                <span className="block font-bold text-slate-700">Parcel Baseline Data:</span>
                <div className="mt-2 grid grid-cols-3 gap-2 text-slate-600">
                  <div>
                    <span className="block text-[11px] text-slate-400">Soil pH</span>
                    <strong>{currentField.soil_ph} pH</strong>
                  </div>
                  <div>
                    <span className="block text-[11px] text-slate-400">Organic Matter</span>
                    <strong>{currentField.organic_matter}%</strong>
                  </div>
                  <div>
                    <span className="block text-[11px] text-slate-400">Water Source</span>
                    <strong className="truncate block">{currentField.water_source}</strong>
                  </div>
                </div>
              </div>
            )}

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600">Current Crop Stage *</label>
              <div className="mt-1.5 grid grid-cols-2 gap-2 text-xs">
                {[
                  ["seedling", "Seedling / Germination"],
                  ["vegetative", "Vegetative Growth"],
                  ["flowering", "Flowering & Fruit Set"],
                  ["mature", "Mature / Pre-Harvest"],
                ].map(([value, label]) => (
                  <button
                    type="button"
                    key={value}
                    onClick={() => setCropStage(value)}
                    className={`rounded-xl border p-2.5 text-left font-semibold transition ${
                      cropStage === value
                        ? "border-[#16875f] bg-[#e0f5eb] text-[#16875f]"
                        : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
                    }`}
                  >
                    {label}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600">Recent Rainfall (Past 7 Days) *</label>
              <select
                value={rainfallRecent}
                onChange={(e) => setRainfallRecent(e.target.value)}
                className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm font-medium text-slate-800 outline-none focus:border-[#16875f]"
              >
                <option value="Low (<25mm)">Low (&lt;25mm) / Dry Spell</option>
                <option value="Moderate (25-50mm)">Moderate (25-50mm) / Adequate</option>
                <option value="Heavy (>50mm)">Heavy (&gt;50mm) / Saturated</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600">Observed Issues / Symptoms</label>
              <select
                value={observedIssues}
                onChange={(e) => setObservedIssues(e.target.value)}
                className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm font-medium text-slate-800 outline-none focus:border-[#16875f]"
              >
                <option value="None">None / Healthy Canopy</option>
                <option value="Leaf Yellowing (N-deficiency)">Leaf Yellowing (N-deficiency)</option>
                <option value="Stunted Growth & Purple Leaves">Stunted Growth & Purple Leaves (P-deficiency)</option>
                <option value="Marginal Leaf Scorching">Marginal Leaf Scorching (K-deficiency)</option>
                <option value="Severe Pest Infestation">Severe Pest Infestation</option>
              </select>
            </div>

            <button
              type="submit"
              disabled={isGenerating}
              className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#16875f] px-6 py-3 text-sm font-bold text-white shadow-md hover:bg-[#064b3b] disabled:opacity-50"
            >
              <RefreshCw size={18} className={isGenerating ? "animate-spin" : ""} />
              {isGenerating ? "Executing Agronomic Rules..." : "Evaluate & Generate Advisory"}
            </button>
          </form>
        </section>

        {/* Output Cards Display */}
        <section className="space-y-6">
          <h3 className="text-xl font-bold tracking-tight text-[#123d35]">Generated Advisory Plan</h3>

          {activeAdvisories ? (
            <div className="space-y-5 animate-fadeIn">
              {/* Fertilizer Plan Card */}
              {activeAdvisories.fertilizer && (
                <div className="rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm">
                  <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                    <div className="flex items-center gap-2.5">
                      <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#e0f5eb] text-[#16875f]">
                        <Sprout size={20} />
                      </div>
                      <h4 className="text-base font-extrabold text-[#123d35]">Fertilizer Plan</h4>
                    </div>
                    <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">
                      {activeAdvisories.fertilizer.crop_stage} Stage
                    </span>
                  </div>

                  <p className="mt-3 text-xs font-semibold text-slate-500">
                    Rule: <span className="text-slate-700">{activeAdvisories.fertilizer.rule_applied}</span>
                  </p>

                  <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-relaxed text-slate-800 border border-slate-100">
                    {activeAdvisories.fertilizer.output_text?.replace(/\*/g, "")}
                  </div>
                </div>
              )}

              {/* Irrigation Schedule Card */}
              {activeAdvisories.irrigation && (
                <div className="rounded-2xl border border-blue-200 bg-white p-6 shadow-sm">
                  <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                    <div className="flex items-center gap-2.5">
                      <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-100 text-blue-700">
                        <Droplets size={20} />
                      </div>
                      <h4 className="text-base font-extrabold text-[#123d35]">Irrigation Schedule</h4>
                    </div>
                    <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">
                      {activeAdvisories.irrigation.rainfall_recent}
                    </span>
                  </div>

                  <p className="mt-3 text-xs font-semibold text-slate-500">
                    Rule: <span className="text-slate-700">{activeAdvisories.irrigation.rule_applied}</span>
                  </p>

                  <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-relaxed text-slate-800 border border-slate-100">
                    {activeAdvisories.irrigation.output_text?.replace(/\*/g, "")}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white/60 p-10 text-center">
              <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e0f5eb] text-[#16875f]">
                <Compass size={28} />
              </div>
              <h4 className="mt-4 text-base font-bold text-[#123d35]">No Active Advisory Generated</h4>
              <p className="mt-2 max-w-sm text-xs leading-relaxed text-slate-500">
                Select your field plot and parameters on the left and click <strong>Evaluate & Generate Advisory</strong> to compute rule-based fertilizer & irrigation instructions.
              </p>
            </div>
          )}

          {/* Historical Advisory Log */}
          {recentRecommendations.length > 0 && (
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs">
              <h4 className="text-sm font-bold text-slate-700">Recent Rule Output History</h4>
              <div className="mt-4 divide-y divide-slate-100">
                {recentRecommendations.slice(0, 3).map((r) => (
                  <div key={r.id} className="py-3 text-xs">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-[#123d35]">{r.field_name || "Field Plot"}</span>
                      <span className="rounded-md bg-slate-100 px-2 py-0.5 font-semibold text-slate-600 capitalize">
                        {r.type}
                      </span>
                    </div>
                    <p className="mt-1 text-slate-600 line-clamp-2">{r.output_text?.replace(/\*/g, "")}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
